name = "fe-dbt"
type = "webpack"
account_id = "" # 你的 Cloudflare 账户 ID
workers_dev = true
route = ""
zone_id = "" # 如果你有自定义域名，填写对应的 zone ID

[site]
bucket = ".next/static"
entry-point = "_worker"

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
name = "fe-dbt-prod"

[env.staging]
name = "fe-dbt-staging" 